FROM r-base:4.1.2

RUN Rscript -e 'install.packages("ggplot2", repos="https://cloud.r-project.org")'
RUN Rscript -e 'install.packages("dplyr", repos="https://cloud.r-project.org")'
RUN Rscript -e 'install.packages("tidyr", repos="https://cloud.r-project.org")'
RUN Rscript -e 'install.packages("magrittr", repos="https://cloud.r-project.org")'
